CREATE OR REPLACE FUNCTION RANDOM_INT(lhs BIGINT, rhs BIGINT)
    RETURNS BIGINT
    LANGUAGE plpgsql
AS
$$
BEGIN
    RETURN FLOOR(RANDOM() * (rhs - lhs + 1) + lhs);
END;
$$;

CREATE OR REPLACE FUNCTION RANDOM_NUMERIC(lhs NUMERIC, rhs NUMERIC)
    RETURNS NUMERIC
    LANGUAGE plpgsql
AS
$$
BEGIN
    RETURN RANDOM() * (rhs - lhs + 1) + lhs;
END;
$$;

CREATE OR REPLACE FUNCTION RANDOM_TIMESTAMP(lhs TIMESTAMP, rhs TIMESTAMP)
    RETURNS TIMESTAMP
    LANGUAGE plpgsql
AS
$$
BEGIN
    RETURN RANDOM() * (rhs - lhs) + lhs;
END;
$$;

CREATE OR REPLACE FUNCTION RANDOM_STRING(len INT)
    RETURNS VARCHAR
    LANGUAGE plpgsql
AS
$$
BEGIN
    RETURN SUBSTR(MD5(RANDOM()::TEXT), 0, len + 1);
END;
$$;
